# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/114LQKKNoXnqRET0zxlVrlOn6ZbOJTHBl
"""

import pandas as pd



INPUT_PATH = '../data/raw/burnout_data.csv'
OUTPUT_PATH = '../data/processed/cleaned_burnout_data.csv'

MEDIAN_FILL_COLS = [
    'social_media_hours',
    'deep_work_hours',
    'sleep_hours',
    'motivation_level'
]


def load_data(path):
    df = pd.read_csv(path)
    print(f"loaded {len(df)} rows from '{path}'")
    return df


def quick_eda(df):
    print("\n--- quick look ---")
    print(df.head())
    print("\ncolumns:", list(df.columns))
    print("\nnull counts:\n", df.isnull().sum())
    dups = df.duplicated().sum()
    if dups:
        print(f"\nfound {dups} duplicate row(s) — keeping for now, revisit if needed")
    else:
        print("\nno duplicates, good to go")


def clean_columns(df):
    df.columns = df.columns.str.lower().str.replace(" ", "_")
    return df


def fill_nulls(df):
    print("\nnulls before fill:\n", df[MEDIAN_FILL_COLS].isnull().sum())
    for col in MEDIAN_FILL_COLS:
        if col in df.columns:
            df[col] = df[col].fillna(df[col].median())
    print("nulls after fill:\n", df[MEDIAN_FILL_COLS].isnull().sum())
    return df


def add_burnout_category(score):
    if score < 35:
        return 'Low'
    elif score < 60:
        return 'Moderate'
    return 'High'


def add_screen_time_category(hours):
    if hours < 5:
        return 'Low Usage'
    elif hours < 9:
        return 'Medium Usage'
    return 'Heavy Usage'


def feature_engineering(df):
    df['burnout_category'] = df['burnout_risk'].apply(add_burnout_category)
    df['screen_time_category'] = df['daily_screen_time'].apply(add_screen_time_category)

    print("\nsample of new columns:")
    print(df[['burnout_risk', 'burnout_category', 'daily_screen_time', 'screen_time_category']].head())
    return df


def save_data(df, path):
    df.to_csv(path, index=False)
    print(f"\nsaved cleaned data to '{path}'")


def run_pipeline():
    df = load_data(INPUT_PATH)
    quick_eda(df)
    df = clean_columns(df)
    df = fill_nulls(df)
    df = feature_engineering(df)
    save_data(df, OUTPUT_PATH)
    print("\ndone.")


if __name__ == '__main__':
    run_pipeline()
